// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ReactController from "./react_controller"
application.register("react", ReactController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import SidebarController from "./sidebar_controller"
application.register("sidebar", SidebarController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import ProjectFormController from "./project_form_controller"
application.register("project-form", ProjectFormController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import AwsOnboardController from "./aws_onboard_controller"
application.register("aws-onboard", AwsOnboardController)

import AzureCredentialsController from "./azure_credentials_controller"
application.register("azure-credentials", AzureCredentialsController)

import AzureOnboardController from "./azure_onboard_controller"
application.register("azure-onboard", AzureOnboardController)

import ProjectListController from "./project_list_controller"
application.register("project-list", ProjectListController)

import FilterController from "./filter_controller"
application.register("filter", FilterController)

import CanvasController from "./canvas_controller"
application.register("canvas", CanvasController)

import CatalogController from "./catalog_controller"
application.register("catalog", CatalogController)

import ConnectController from "./connect_controller"
application.register("connect", ConnectController)

import PropertiesController from "./properties_controller"
application.register("properties", PropertiesController)

import CanvasMainController from "./canvas_main_controller"
application.register("canvas-main", CanvasMainController)

import SidebarNavController from "./sidebar_nav_controller"
application.register("sidebar-nav", SidebarNavController)

import RpanelController from "./rpanel_controller"
application.register("rpanel", RpanelController)

import CmdPaletteController from "./cmd_palette_controller"
application.register("cmd-palette", CmdPaletteController)

import CascadingSelectController from "./cascading_select_controller"
application.register("cascading-select", CascadingSelectController)

import EntityFilterController from "./entity_filter_controller"
application.register("entity-filter", EntityFilterController)

import DocumentationController from "./documentation_controller"
application.register("documentation", DocumentationController)

